name: Python LEI

on:
  pull_request:
    branches: '*'
  push:
    branches: ["master"]
    tags: ["*"]
jobs:
  CI:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11] # Specify Python versions here
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/ci.txt
        pip install -e .

    - name: Download Data
      run: python -c "from python_lei.utils import Download; Download(_is_actions=True)"

    - name: Test
      run: python -m pytest tests/

    - name: Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        pip install codecov
        codecov

  CD:
    needs: CI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: PyPi Deploy preparation
      run: |
        pip install --upgrade setuptools wheel
        python setup.py sdist bdist_wheel --universal
    - name: PyPi Deploy
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: ${{ secrets.PYPI_USER }}
        password: ${{ secrets.PYPI_PASSWORD }}
